### ISSUE TITLE
Object Chaining

### ISSUE THREAD

**Issue by mstone121** [mstone121/php-object-sql#1]
This library is pretty simple. It doesn't adopt the usual chaining pattern used by other similar libraries, i.e.:
```php
$query = Query::select('id', 'label')->from('users')->where('user_type', 'admin');
```

This is intentional. The idea of this project is to represent each of the components of a SQL query as an object which can be interchanged/modified independently of the other components of the query. 

Chaining flips this idea around: a single query object supplies all of its subcomponents. I believe this would add complexity to the implementation and also detract from the original purpose of the library.

**Comment by polartar** [comment]
@mstone121 Is this still not working?

**Comment by polartar** [comment]
Thanks for your checking. Matt, this is Mike, former developer at GSU.
How is it going? When you have time, could you email me to "polaris.center@outlook.com"?
